import type { GalSwarmComputeProfile, GalSwarmProviderIntegrationProfile } from '../contracts.js'

export function defaultGalSwarmProviderIntegrationProfiles(): GalSwarmProviderIntegrationProfile[] {
  return [
    {
      provider: 'runpod',
      lifecycleSurface: 'pod',
      billingGranularity: 'second',
      canScaleToZero: true,
      supportsStop: true,
      supportsTerminate: true,
      supportsSpot: true,
      supportsReservations: true,
      supportsServerless: true,
      minBillableSeconds: 1,
      typicalStartupSeconds: 90,
      typicalShutdownSeconds: 30,
      metricsSurfaces: ['runtime_api', 'container_metrics'],
      adapterPackage: '@stratus/gpu-provider-runpod',
      sdkPackages: ['REST API', 'GraphQL API', 'runpodctl'],
      authSecretNames: ['RUNPOD_API_KEY'],
      notes: 'Best first burst path: low-friction pod lifecycle, second-level billing, and direct runtime GPU metrics.',
    },
    {
      provider: 'crusoe',
      lifecycleSurface: 'vm',
      billingGranularity: 'minute',
      canScaleToZero: true,
      supportsStop: true,
      supportsTerminate: true,
      supportsSpot: true,
      supportsReservations: true,
      supportsServerless: false,
      minBillableSeconds: 60,
      typicalStartupSeconds: 180,
      typicalShutdownSeconds: 60,
      metricsSurfaces: ['prometheus', 'dcgm_agent'],
      adapterPackage: '@stratus/gpu-provider-crusoe',
      sdkPackages: ['Crusoe API Gateway', 'Crusoe CLI', 'Terraform provider'],
      authSecretNames: ['CRUSOE_API_TOKEN', 'CRUSOE_PROJECT_ID', 'CRUSOE_MONITORING_TOKEN'],
      notes: 'Best second path for HGX-style observability and enterprise capacity; requires Watch Agent for VM metrics.',
    },
    {
      provider: 'gcp',
      lifecycleSurface: 'vm',
      billingGranularity: 'minute',
      canScaleToZero: true,
      supportsStop: true,
      supportsTerminate: true,
      supportsSpot: true,
      supportsReservations: true,
      supportsServerless: false,
      minBillableSeconds: 60,
      typicalStartupSeconds: 300,
      typicalShutdownSeconds: 90,
      metricsSurfaces: ['cloud_monitoring', 'dcgm_agent'],
      adapterPackage: '@stratus/gpu-provider-gcp',
      sdkPackages: ['@google-cloud/compute', 'google-cloud-monitoring'],
      authSecretNames: ['GOOGLE_APPLICATION_CREDENTIALS', 'GCP_PROJECT_ID', 'GCP_ZONE'],
      notes: 'Good fallback for quota-managed A3/A4 capacity and Cloud Monitoring; generally worse for exact short H200 bursts.',
    },
    {
      provider: 'aws',
      lifecycleSurface: 'vm',
      billingGranularity: 'second',
      canScaleToZero: true,
      supportsStop: true,
      supportsTerminate: true,
      supportsSpot: true,
      supportsReservations: true,
      supportsServerless: false,
      minBillableSeconds: 60,
      typicalStartupSeconds: 360,
      typicalShutdownSeconds: 90,
      metricsSurfaces: ['cloud_monitoring', 'dcgm_agent'],
      adapterPackage: '@stratus/gpu-provider-aws',
      sdkPackages: ['@aws-sdk/client-ec2', '@aws-sdk/client-cloudwatch'],
      authSecretNames: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION'],
      notes: 'Strong API surface, but H200-class access often needs Capacity Blocks or reservations, which hurts short bursts.',
    },
    {
      provider: 'azure',
      lifecycleSurface: 'vm',
      billingGranularity: 'minute',
      canScaleToZero: true,
      supportsStop: true,
      supportsTerminate: true,
      supportsSpot: true,
      supportsReservations: true,
      supportsServerless: false,
      minBillableSeconds: 60,
      typicalStartupSeconds: 360,
      typicalShutdownSeconds: 120,
      metricsSurfaces: ['cloud_monitoring', 'dcgm_agent'],
      adapterPackage: '@stratus/gpu-provider-azure',
      sdkPackages: ['@azure/arm-compute', '@azure/monitor-query', '@azure/identity'],
      authSecretNames: ['AZURE_CLIENT_ID', 'AZURE_TENANT_ID', 'AZURE_CLIENT_SECRET', 'AZURE_SUBSCRIPTION_ID'],
      notes: 'Use deallocate/delete for compute shutdown; GPU metrics require guest/agent instrumentation.',
    },
  ]
}

export function defaultGalSwarmPreflightComputeProfiles(): GalSwarmComputeProfile[] {
  return [
    {
      id: 'gcp-l4-spot-glm-4-9b-tool-call-smoke',
      provider: 'gcp',
      label: 'GCP L4 Spot GLM 4 9B tool-call smoke',
      region: 'us-east4',
      zone: 'us-east4-a',
      spot: true,
      modelId: 'zai-org/glm-4-9b-chat-hf',
      purpose: 'tool_calling_smoke',
      maxDurationMinutes: 15,
      maxSpendUsd: 0.1,
      cpuCores: 4,
      memoryGb: 16,
      gpuType: 'NVIDIA L4',
      gpuCount: 1,
      diskGb: 100,
      image: 'vllm/vllm-openai:latest',
      imageRef: 'us-docker.pkg.dev/gal-run/gal-swarm-preflight/vllm-openai:latest',
      modelCache: {
        uri: 'gs://gal-swarm-preflight-model-cache/hf/zai-org/glm-4-9b-chat-hf',
        mode: 'hydrate_on_startup',
        mountPath: '/models',
        expectedHitRate: 0.85,
        hydrateTimeoutSeconds: 300,
      },
      startupBudgetSeconds: 600,
      readinessProbe: {
        type: 'http',
        path: '/v1/models',
        port: 8000,
        timeoutSeconds: 10,
        intervalSeconds: 10,
      },
      shutdownPolicy: {
        maxDurationSeconds: 900,
        deleteInstance: true,
        deleteBootDisk: true,
        cleanupNetwork: true,
      },
      tools: ['vllm', 'openai-compatible-api', 'tool-call-parser', 'cloud-monitoring'],
    },
    {
      id: 'gcp-l4-spot-qwen2-5-coder-7b-coding-smoke',
      provider: 'gcp',
      label: 'GCP L4 Spot Qwen2.5 Coder 7B coding smoke',
      region: 'us-east4',
      zone: 'us-east4-a',
      spot: true,
      modelId: 'Qwen/Qwen2.5-Coder-7B-Instruct',
      purpose: 'coding_smoke',
      maxDurationMinutes: 15,
      maxSpendUsd: 0.1,
      cpuCores: 4,
      memoryGb: 16,
      gpuType: 'NVIDIA L4',
      gpuCount: 1,
      diskGb: 100,
      image: 'vllm/vllm-openai:latest',
      imageRef: 'us-docker.pkg.dev/gal-run/gal-swarm-preflight/vllm-openai:latest',
      modelCache: {
        uri: 'gs://gal-swarm-preflight-model-cache/hf/Qwen/Qwen2.5-Coder-7B-Instruct',
        mode: 'hydrate_on_startup',
        mountPath: '/models',
        expectedHitRate: 0.85,
        hydrateTimeoutSeconds: 300,
      },
      startupBudgetSeconds: 600,
      readinessProbe: {
        type: 'http',
        path: '/v1/models',
        port: 8000,
        timeoutSeconds: 10,
        intervalSeconds: 10,
      },
      shutdownPolicy: {
        maxDurationSeconds: 900,
        deleteInstance: true,
        deleteBootDisk: true,
        cleanupNetwork: true,
      },
      tools: ['vllm', 'openai-compatible-api', 'coding-smoke', 'cloud-monitoring'],
    },
  ]
}
