export { Recorder, RecordingConfigSchema, type RecordingConfig } from './core/recorder.js';
export { VideoProcessor, type VideoInfo, type ProcessOptions } from './core/video-processor.js';
export { DemoScriptRunner, DemoStepSchema, DemoScriptSchema, type DemoStep, type DemoScript } from './core/demo-runner.js';
export { WindowDetector, type WindowInfo, type WindowDetectionOptions } from './core/window-detector.js';
export { ScreenCapture, type ScreenshotOptions, type RecordingSession } from './core/screen-capture.js';
export { ZoomEngine, ZoomConfigSchema, type ZoomConfig, type ZoomRegion, type ZoomKeyframe } from './effects/zoom.js';
export { CursorEngine, CursorConfigSchema, type CursorConfig, type CursorPosition, type ClickEvent, type SmoothedPosition } from './effects/cursor.js';
export { OverlayEngine, KeystrokeConfigSchema, TextOverlayConfigSchema, type KeystrokeConfig, type TextOverlayConfig } from './effects/overlay.js';
export { TTSEngine, TTSEngineConfigSchema, type TTSEngineConfig, type VoiceoverSegment, type TTSResult } from './tts/index.js';
export { TimelineEditor, TimelineClipSchema, TimelineTrackSchema, type TimelineClip, type TimelineTrack, type TimelineState } from './timeline/editor.js';
export { Renderer, RenderConfigSchema, type RenderConfig } from './renderer/index.js';
