use anyhow::Result;
use clap::{Parser, Subcommand};
use colored::*;

use crate::client::ApiClient;

#[derive(Parser)]
pub struct TemplateArgs {
    #[command(subcommand)]
    pub command: TemplateCommands,
}

#[derive(Subcommand)]
pub enum TemplateCommands {
    /// List available templates
    List {
        /// Output as JSON
        #[arg(long)]
        json: bool,
    },
    /// Generate from template
    Generate {
        /// Template name
        name: String,
        /// Output directory
        #[arg(default_value = ".")]
        output: String,
    },
}

pub async fn run(_client: ApiClient, args: TemplateArgs) -> Result<()> {
    match args.command {
        TemplateCommands::List { json } => cmd_list(json).await,
        TemplateCommands::Generate { name, output } => cmd_generate(&name, &output).await,
    }
}

async fn cmd_list(json: bool) -> Result<()> {
    // Built-in templates
    let templates = vec![
        serde_json::json!({
            "name": "claude-config",
            "description": "Basic Claude Code configuration template",
            "files": ["CLAUDE.md", ".gal/config.yaml"],
        }),
        serde_json::json!({
            "name": "cursor-config",
            "description": "Cursor editor configuration template",
            "files": [".cursorrules", ".gal/config.yaml"],
        }),
        serde_json::json!({
            "name": "gal-project",
            "description": "Full GAL project setup with hooks and config",
            "files": ["CLAUDE.md", ".gal/config.yaml", ".gal/.galignore"],
        }),
        serde_json::json!({
            "name": "minimal",
            "description": "Minimal .gal directory setup",
            "files": [".gal/config.yaml"],
        }),
    ];

    if json {
        println!("{}", serde_json::to_string_pretty(&templates)?);
        return Ok(());
    }

    println!("\n{} Available Templates ({})", "Templates:".blue().bold(), templates.len());
    println!("{}", "─".repeat(50).dimmed());

    for tmpl in &templates {
        let name = tmpl.get("name").and_then(|v| v.as_str()).unwrap_or("");
        let desc = tmpl.get("description").and_then(|v| v.as_str()).unwrap_or("");
        println!("  {} {} - {}", "•".cyan(), name.white(), desc);
    }
    println!();
    println!("  {} Use: gal template generate <name> [output-dir]", "(Usage)".dimmed());
    println!();

    Ok(())
}

async fn cmd_generate(name: &str, output: &str) -> Result<()> {
    let out_dir = std::path::Path::new(output);

    match name {
        "claude-config" => {
            std::fs::create_dir_all(out_dir.join(".gal"))?;
            std::fs::write(
                out_dir.join("CLAUDE.md"),
                "# CLAUDE.md\n\nGenerated by GAL CLI template.\n\n## Guidelines\n- Follow organization AI policies\n- Use approved config from gal sync --pull\n",
            )?;
            std::fs::write(
                out_dir.join(".gal").join("config.yaml"),
                "# GAL Config\nversion: 1\nplatform: claude\n",
            )?;
            println!("  {} Claude config template generated in {}", "✓".green(), output);
        }
        "cursor-config" => {
            std::fs::create_dir_all(out_dir.join(".gal"))?;
            std::fs::write(out_dir.join(".cursorrules"), "# Cursor Rules\n\n")?;
            std::fs::write(
                out_dir.join(".gal").join("config.yaml"),
                "# GAL Config\nversion: 1\nplatform: cursor\n",
            )?;
            println!("  {} Cursor config template generated in {}", "✓".green(), output);
        }
        "gal-project" => {
            std::fs::create_dir_all(out_dir.join(".gal"))?;
            std::fs::write(
                out_dir.join("CLAUDE.md"),
                "# CLAUDE.md\n\nManaged by GAL CLI.\n",
            )?;
            std::fs::write(
                out_dir.join(".gal").join("config.yaml"),
                "# GAL Config\nversion: 1\norganization: default\n",
            )?;
            std::fs::write(out_dir.join(".gal").join(".galignore"), "node_modules\ntarget\n.git\n")?;
            println!("  {} GAL project template generated in {}", "✓".green(), output);
        }
        "minimal" => {
            std::fs::create_dir_all(out_dir.join(".gal"))?;
            std::fs::write(
                out_dir.join(".gal").join("config.yaml"),
                "# GAL Config\nversion: 1\n",
            )?;
            println!("  {} Minimal template generated in {}", "✓".green(), output);
        }
        _ => {
            println!("  {} Unknown template: {}", "✗".red(), name);
            println!("  {} Use 'gal template list' to see available templates", "(Hint)".dimmed());
            return Ok(());
        }
    }

    println!();
    Ok(())
}
