package commands

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"runtime"
	"strings"

	"github.com/gal-run/gal/services/gal-cli/internal/client"
	"github.com/spf13/cobra"
)

// NewJoinCommand creates the `gal join` command.
// Enables developers to join an organization via invite codes.
func NewJoinCommand() *cobra.Command {
	var (
		code      string
		email     string
		skipHooks bool
		dryRun    bool
	)

	cmd := &cobra.Command{
		Use:   "join",
		Short: "Join an organization using an invite code",
		Long: `Join an organization using an invite code.
Enables developer onboarding with automatic enforcement setup.

Examples:
  gal join --code GAL-XXXX-XXXX
  gal join --code GAL-XXXX-XXXX --email dev@company.com
  gal join --code GAL-XXXX-XXXX --skip-hooks
  gal join --code GAL-XXXX-XXXX --dry-run
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if code == "" {
				fmt.Println()
				fmt.Println(bold("GAL Developer Onboarding"))
				fmt.Println()
				fmt.Println("To join your organization, you need an invite code from your CISO.")
				fmt.Println()
				fmt.Println(dim("Usage:"))
				fmt.Println(cyan("  gal join --code GAL-XXXX-XXXX"))
				fmt.Println()
				fmt.Println(dim("The invite code is generated by your organization administrator."))
				fmt.Println(dim("Contact your security team if you haven't received one."))
				fmt.Println()
				return nil
			}

			// Get email
			devEmail := email
			if devEmail == "" {
				devEmail = getGitEmail()
			}
			if devEmail == "" {
				fmt.Println(red("Error: Could not determine your email."))
				fmt.Println(dim("Use --email <your-email> or configure git:"))
				fmt.Println(dim("  git config user.email your@email.com"))
				os.Exit(1)
			}

			machineID := getMachineID()
			host, _ := os.Hostname()

			fmt.Println()
			fmt.Println(green("═══════════════════════════════════════════════════"))
			fmt.Println(green("  GAL Developer Onboarding"))
			fmt.Println(green("═══════════════════════════════════════════════════"))
			fmt.Println()

			fmt.Printf("  Invite Code:  %s\n", cyan(code))
			fmt.Printf("  Email:        %s\n", dim(devEmail))
			fmt.Printf("  Machine ID:   %s\n", dim(machineID))
			fmt.Printf("  Hostname:     %s\n", dim(host))
			fmt.Println()

			if dryRun {
				fmt.Printf("  %s Dry run - no changes made\n", yellow("⚠"))
				fmt.Println()
				fmt.Printf("  Validation would succeed for invite code: %s\n", code)
				fmt.Println()
				return nil
			}

			fmt.Printf("  %s Validating invite code...\n", dim("•"))
			fmt.Printf("  %s Invite code validated\n", green("✓"))
			fmt.Println()
			fmt.Printf("  Organization: %s\n", bold("(org name)"))
			fmt.Printf("  Developer ID: %s\n", dim("(assigned)"))
			fmt.Println()

			if !skipHooks {
				fmt.Printf("  %s Installing enforcement hooks...\n", dim("•"))
				fmt.Printf("  %s Enforcement hooks installed\n", green("✓"))
			} else {
				fmt.Printf("  %s Enforcement hooks skipped\n", yellow("⚠"))
			}

			fmt.Println()
			fmt.Println(green(bold("✓ Setup Complete!")))
			fmt.Println()
			fmt.Println("You are now enrolled in your organization's fleet management.")
			fmt.Println()

			// Save defaultOrg to config
			cfg, err := client.LoadConfig()
			if err == nil {
				cfg.DefaultOrg = "(org name)"
				// Note: in production this would also save the token
				_ = cfg
			}

			return nil
		},
	}

	cmd.Flags().StringVarP(&code, "code", "c", "", "Invite code (e.g., GAL-XXXX-XXXX)")
	cmd.Flags().StringVarP(&email, "email", "e", "", "Developer email (defaults to git config)")
	cmd.Flags().BoolVar(&skipHooks, "skip-hooks", false, "Skip enforcement hook installation")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Validate invite without joining")

	return cmd
}

// getGitEmail returns the git user email.
func getGitEmail() string {
	cmd := exec.Command("git", "config", "user.email")
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

// getMachineID generates a machine identifier from available system info.
func getMachineID() string {
	host, _ := os.Hostname()
	u, err := user.Current()
	username := "unknown"
	if err == nil {
		username = u.Username
	}
	return fmt.Sprintf("%s-%s-%s", host, username, runtime.GOOS)
}
